package model;

public enum Filter {
	STANDARD, MIT_ARCHIV, NUR_ARCHIV, NICHT_ABG_AKTUELL, NICHT_ABG_ALLE, NICHT_KORR_AKTUELL, NICHT_KORR_ALLE, NICHT_EXP_AKTUELL, NICHT_EXP_ALLE, EXP_AKTUELL, EXP_ALLE;
}

